### PR TITLE
Polish translation revised

### PR DESCRIPTION
**Pull request by Roberciiik**
Fixed many issues with Polish translation.

### CODE REVIEW

**Comment by GwendolyneFreddy** [comment]
I will wait a couple of days, in case other translators provide fixes. But don't worry, a new version will be released before Xmas. ;)

**Comment by skellytz** [comment]
Let's keep master even with the current release and use devel for v1.22 updates.

**Comment by GwendolyneFreddy** [comment]
It's the first time I will merge a PR into another branch. 😉 
As both Robert and you did not modify the same files, I guess they won't be any conflict and it will be safe merging it.

**Comment by skellytz** [comment]
Yes, I think master should always be release-ready. We'll then squash and merge devel when v1.22 is done to keep things neat and tidy.

**Comment by GwendolyneFreddy** [comment]
OK. I will let you merge it. Thanks. I have got plenty of mods to update and it will save my time.

As the French translation is very old, let me know when you intend to release v1.22, so that I can update it with new content, if needed.

**Pull request merged**
